const LoginError = {
	EMAIL_MISSING: 'LOGIN_ERROR_EMAIL_MISSING',
	INVALID: 'LOGIN_ERROR_INVALID',
	UNKNOWN: 'LOGIN_ERROR_UNKNOWN'
} as const;

const SignupError = {
	EMAIL_TAKEN: 'SIGNUP_ERROR_EMAIL_TAKEN',
	VALIDATION: 'SIGNUP_ERROR_VALIDATION',
	UNKNOWN: 'SIGNUP_ERROR_UNKNOWN'
} as const;

export { LoginError, SignupError };
